services:
  barito-fluent-bit:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      tags:
        - docker.io/juneardoc/barito-fluent-bit:dev
    container_name: barito-fluent-bit
    volumes:
      - ./examples/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - ./foobar.log:/tmp/log-example:ro
    command:
      - -c
      - /fluent-bit/etc/fluent-bit.conf
    ports:
      - "2020:2020"
      - "2021:2021"