name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Build Go binary
        run: |
            export VERSION=$(git describe --tags HEAD)-$(git rev-parse HEAD)
            export BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
            make out_barito_batch_k8s

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: out_barito_batch_k8s-${{ matrix.os }}-${{ matrix.arch }}.so
          path: out_barito_batch_k8s.so

#   docker:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     needs: build
#     strategy:
#       matrix:
#         platform: [linux/amd64, linux/arm64]
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3

#       - name: Log in to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: ${{ matrix.platform }}
#           push: true
#           tags: |
#             your-dockerhub-username/your-image-name:latest
#             your-dockerhub-username/your-image-name:${{ matrix.platform }}
#             your-dockerhub-username/your-image-name:${{ github.sha }}
#             your-dockerhub-username/your-image-name:${{ github.ref_name }}