name: Go Build and Docker Push

on:
    release:
        types: [published]

jobs:
    docker:
        name: Build and Push Docker Images
        strategy:
            matrix:
                platform: [linux/amd64, linux/arm64]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: login to ghcr
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and Push Docker Images
              run: |
                export DOCKER_DEFAULT_PLATFORM=${{ matrix.platform }}
                make build-and-push

    binary:
        name: Build Go Binaries
        strategy:
            matrix:
                os: [ubuntu-22.04]
                arch: [amd64, arm64]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.23.2'
            - name: Build Go Binary
              run: |
                export VERSION=$(git describe --tags HEAD)-$(git rev-parse HEAD)
                export BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
                make out_barito_batch_k8s
                mv out_barito_batch_k8s.so out_barito_batch_k8s-${{ matrix.arch }}.so
            - uses: softprops/action-gh-release@v2
              with:
                files: out_barito_batch_k8s-${{matrix.arch}}.so