name: Go Build and Docker Push

on:
    release:
        types: [published]

jobs:
    docker:
        name: Build and Push Docker Images
        strategy:
            matrix:
                platform: [linux/amd64, linux/arm64]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and Push Docker Images
              run: |
                make build-and-push

    binary:
        name: Build Go Binaries
        strategy:
            matrix:
                os: [ubuntu-22.04]
                arch: [amd64, arm64]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.23.2'
            - name: Build Go Binary
              run: |
                export VERSION=$(git describe --tags HEAD)-$(git rev-parse HEAD)
                export BUILD_TIME=$(date -u '+%Y-%m-%dT%H:%M:%SZ')
                make out_barito_batch_k8s
                mv out_barito_batch_k8s.so out_barito_batch_k8s-${{ matrix.arch }}.so
            - uses: softprops/action-gh-release@v2
              with:
                files: out_barito_batch_k8s-${{matrix.arch}}.so
#   docker:
#     name: Build and Push Docker Image
#     runs-on: ubuntu-latest
#     needs: build
#     strategy:
#       matrix:
#         platform: [linux/amd64, linux/arm64]
#     steps:
#       - name: Checkout source code
#         uses: actions/checkout@v3

#       - name: Log in to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v5
#         with:
#           context: .
#           platforms: ${{ matrix.platform }}
#           push: true
#           tags: |
#             your-dockerhub-username/your-image-name:latest
#             your-dockerhub-username/your-image-name:${{ matrix.platform }}
#             your-dockerhub-username/your-image-name:${{ github.sha }}
#             your-dockerhub-username/your-image-name:${{ github.ref_name }}